stages:
  - build
  - package
  - release

include:
  - project: "m7/ci/m7-ci-template"
    ref: master
    file:
      - "/front-simple/astra-16-build.yml"
      - "/front-simple/astra-16-deb.yml"
      - "/front-simple/astra-16-upload-deb-to-nexus.yml"
      - "/front-simple/astra-16-gitlab-tag.yml"

